/*
* generated by Xtext
*/
package org.grammaticalframework.eclipse;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GFUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.grammaticalframework.eclipse.ui.internal.GFActivator.getInstance().getInjector("org.grammaticalframework.eclipse.GF");
	}
	
}
