/*
* generated by Xtext
*/
package org.grammaticalframework.eclipse.ui.contentassist;

import org.grammaticalframework.eclipse.ui.contentassist.AbstractGFProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GFProposalProvider extends AbstractGFProposalProvider {

}
