/*
 * generated by Xtext
 */
package org.grammaticalframework.eclipse;

import org.grammaticalframework.eclipse.naming.GFQualifiedNameProvider;
import org.grammaticalframework.eclipse.resource.GFResourceDescriptionStrategy;
import org.grammaticalframework.eclipse.scoping.GFGlobalScopeProvider;
import org.grammaticalframework.eclipse.scoping.GFScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class GFRuntimeModule extends
		org.grammaticalframework.eclipse.AbstractGFRuntimeModule {

	// Ref: http://www.eclipse.org/forums/index.php/t/217911/
	
	@Override
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return GFQualifiedNameProvider.class;
	}
	
	
	public Class<? extends org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return GFResourceDescriptionStrategy.class;
	}

	
	@Override
	public Class<? extends org.eclipse.xtext.scoping.IScopeProvider> bindIScopeProvider() {
		return GFScopeProvider.class;
	}
	@Override
	public Class<? extends org.eclipse.xtext.scoping.IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return GFGlobalScopeProvider.class;
	}


}
